itk-dev/dagplejelager

- .github/workflows/pr.yaml
- README.md
- composer.json
- composer.lock
- docker-compose.yml
- scripts/git/hooks/pre-commit
- web/themes/custom/dagplejelager_theme/templates/README.md
Updates automated code checks.
> Code checks

- CHANGELOG.md
- README.md
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/openid_connect.client.generic.yml
- config/sync/openid_connect.settings.yml
- config/sync/system.action.user_add_role_action.administrator.yml
- config/sync/system.action.user_remove_role_action.administrator.yml
- config/sync/user.mail.yml
- config/sync/user.role.administrator.yml
- config/sync/user.settings.yml
https://jira.itkdev.dk/browse/DAGPLEJ-20
Adds OpenID Connect and configuration.
> DAGPLEJ-20: AD Login

- CHANGELOG.md
- README.md
- composer.json
- composer.lock
- config/sync/core.entity_form_mode.commerce_order.checkout.yml
- config/sync/core.extension.yml
- web/modules/custom/dagplejelager_form/README.md
- web/modules/custom/dagplejelager_form/dagplejelager_form.info.yml
- web/modules/custom/dagplejelager_form/dagplejelager_form.install
- web/modules/custom/dagplejelager_form/dagplejelager_form.libraries.yml
- web/modules/custom/dagplejelager_form/dagplejelager_form.routing.yml
- web/modules/custom/dagplejelager_form/dagplejelager_form.services.yml
- web/modules/custom/dagplejelager_form/js/billing-information-profile.js
- web/modules/custom/dagplejelager_form/src/Commands/DayCarerCommands.php
- web/modules/custom/dagplejelager_form/src/Controller/DayCarerAutoCompleteController.php
- web/modules/custom/dagplejelager_form/src/Entity/Person.php
- web/modules/custom/dagplejelager_form/src/EventSubscriber/FormEventSubscriber.php
- web/modules/custom/dagplejelager_form/src/Helper/DayCarerHelper.php
https://jira.itkdev.dk/browse/DAGPLEJ-62
Adds day carer name and address lookup to the billing information page.
> DAGPLEJ-62: Address lookup

- config/sync/openid_connect.settings.yml
- config/sync/user.role.anonymous.yml
https://jira.itkdev.dk/browse/DAGPLEJ-20
> DAGPLEJ-20: Tweaked user configuration

- config/sync/commerce_checkout.commerce_checkout_flow.default.yml
- config/sync/core.entity_form_display.commerce_order.default.checkout.yml
- config/sync/core.entity_form_display.commerce_order.default.default.yml
- config/sync/core.entity_view_display.commerce_order.default.default.yml
- config/sync/core.entity_view_display.commerce_order.default.user.yml
- config/sync/field.field.commerce_order.default.field_institution_id.yml
- config/sync/field.storage.commerce_order.field_institution_id.yml
https://jira.itkdev.dk/browse/DAGPLEJ-62
Adds missing configuration.
> DAGPLEJ-62: Added missing order fields

- config/sync/block.block.userlogin.yml
- config/sync/field.storage.commerce_product.field_category.yml
- config/sync/user.role.administrator.yml
- config/sync/user.role.anonymous.yml
- config/sync/user.role.authenticated.yml
- config/sync/user.role.manager.yml
- config/sync/views.view.forside.yml
Changed permissions
Added user login block
> DAGPLEJ-23: Changed product permsissions

- config/sync/user.role.administrator.yml
- config/sync/user.role.manager.yml
- web/modules/custom/dagplejelager_form/dagplejelager_form.permissions.yml
- web/modules/custom/dagplejelager_form/dagplejelager_form.routing.yml
Secures the day carer lookup api with a permission.
> DAGPLEJ-24: Add and use custom permission

- web/modules/custom/dagplejelager_form/src/EventSubscriber/FormEventSubscriber.php
https://jira.itkdev.dk/browse/DAGPLEJ-65
> DAGPLEJ-65: Hide prices and status in product forms

- config/sync/core.extension.yml
- config/sync/language/da/commerce_store.commerce_store_type.online.yml
- config/sync/language/da/views.view.commerce_cart_block.yml
- config/sync/language/da/views.view.commerce_cart_form.yml
- config/sync/language/da/views.view.commerce_carts.yml
- config/sync/language/da/views.view.commerce_checkout_order_summary.yml
- config/sync/language/da/views.view.commerce_order_item_table.yml
- config/sync/language/da/views.view.commerce_orders.yml
- config/sync/language/da/views.view.commerce_products.yml
- config/sync/language/da/views.view.commerce_stores.yml
- config/sync/language/da/views.view.commerce_user_orders.yml
- config/sync/language/da/views.view.profiles.yml
- config/sync/views.view.commerce_orders.yml
- config/sync/views.view.commerce_products.yml
- web/modules/custom/dagplejelager_form/dagplejelager_form.info.yml
- web/modules/custom/dagplejelager_form/dagplejelager_form.services.yml
- web/modules/custom/dagplejelager_form/src/EventSubscriber/FormEventSubscriber.php
- web/modules/custom/dagplejelager_form/src/EventSubscriber/ViewsEventSubscriber.php
https://jira.itkdev.dk/browse/DAGPLEJ-33
* Updates orders view with product and product category search
* Adds category (with filter) to products view
> DAGPLEJ-33: Update orders view

- composer.json
- web/themes/custom/dagplejelager_theme/logo.svg
https://jira.itkdev.dk/browse/DAGPLEJ-66
* Adds missing theme default logo
* Installs theme libraries
> Theme logo and libraries

- config/sync/language/da/views.view.forside.yml
- config/sync/views.view.forside.yml
https://jira.itkdev.dk/browse/DAGPLEJ-84
This may not improve the usability of the list …
> DAGPLEJ-84: Replaced bundle product list with description

- config/sync/block.block.dagplejelager_theme_content.yml
- config/sync/block.block.dagplejelager_theme_local_actions.yml
- config/sync/block.block.dagplejelager_theme_local_tasks.yml
- config/sync/block.block.dagplejelager_theme_userlogin.yml
- config/sync/block.block.views_block__product_categories_block_1.yml
- config/sync/views.view.product_categories.yml
https://jira.itkdev.dk/browse/DAGPLEJ-84
Adds weird product list duplication on front page.
> DAGPLEJ-84: Added product category list

- web/modules/custom/dagplejelager_form/dagplejelager_form.install
- web/modules/custom/dagplejelager_form/js/billing-information-profile.js
- web/modules/custom/dagplejelager_form/src/Commands/DayCarerCommands.php
- web/modules/custom/dagplejelager_form/src/Helper/DayCarerHelper.php
https://jira.itkdev.dk/browse/DAGPLEJ-81
> DAGPLEJ-81: Added telephone number to daycarer

- config/sync/language/da/views.view.commerce_orders.yml
https://jira.itkdev.dk/browse/DAGPLEJ-87
> DAGPLEJ-87: Translated filter label

- config/sync/core.extension.yml
- web/modules/custom/dagplejelager_commerce/README.md
- web/modules/custom/dagplejelager_commerce/dagplejelager_commerce.info.yml
- web/modules/custom/dagplejelager_commerce/dagplejelager_commerce.module
- web/modules/custom/dagplejelager_commerce/dagplejelager_commerce.services.yml
- web/modules/custom/dagplejelager_commerce/src/Helper/Helper.php
https://jira.itkdev.dk/browse/DAGPLEJ-86
Removes “Create new order” local action.
> DAGPLEJ-86: Added custom module to remove local action

- config/sync/language/da/views.view.commerce_orders.yml
- config/sync/views.view.commerce_orders.yml
https://jira.itkdev.dk/browse/DAGPLEJ-88
> DAGPLEJ-88: Added grouped order status filter

- config/sync/views.view.commerce_orders.yml
- translations/translations.da.po
- web/modules/custom/dagplejelager_actions/src/TwigExtension/TwigExtension.php
https://jira.itkdev.dk/browse/DAGPLEJ-93
Adds display of order items handling. This may be a hack and there may be a more view-ish way to do it.
> DAGPLEj-93: Order items handling

- .gitattributes
- .github/workflows/pr.yaml
- composer.json
- composer.lock
- docker-compose.server.yml
- docker-compose.yml
- web/modules/custom/dagplejelager_actions/src/EventSubscriber/EntityEventSubscriber.php
- web/modules/custom/dagplejelager_form/src/EventSubscriber/FormEventSubscriber.php
- web/modules/custom/dagplejelager_form/src/EventSubscriber/ViewsEventSubscriber.php
https://jira.itkdev.dk/browse/SUPP0RT-943
Upgrades to PHP 8.1[^1] and cleans up a bit.
[^1]:  Our PHP 7.4 docker images no longer supports MS SQL which is used for getting the list of day carers.
> SUPP0RT-943: Upgraded to PHP 8.1

- .github/workflows/pr.yaml
- CHANGELOG.md
- composer.json
- composer.lock
https://jira.itkdev.dk/browse/SUPP0RT-943
- SUPP0RT-943: Updated facets module
- SUPP0RT-943: Updated change log
> SUPP0RT-943: Update facets module

- CHANGELOG.md
- composer.json
- composer.lock
- web/modules/custom/dagplejelager_form/js/billing-information-profile.js
https://leantime.itkdev.dk/#/tickets/showTicket/225
- 225: Applied patch to Hook Event Dispatcher module
- 225: Updated handling of profile autocompletion
> Profile autocomplete
